<div class="document">
	<?php echo __('Before you start using ImageEngine, you need to obtain a unique application token. If you have not registered yet, please do so here. For future reference, you will find your token in the ImageEngine section on');?> 

	<a target="_blank" href="scientiamobile.com"><?php echo __('account pages.');?></a>
	
	<div class="register"><a target="_blank" href="scientiamobile.com"><?php echo __('Register');?></a></div>

	
</div>




<style type="text/css">
	.document{
		border: 1px solid #adadad;
	    width: 500px;
	    float: right;
	    margin-right: 62px;
	    padding: 18px;
	}
	.document .register{
		background-color: #dbdbdb;
	    color: #514943;
	    border: 1px solid #adadad;
	    width: 79px;
	    margin-top: 10px;
	    padding: 10px;
	    text-align: center;
	}
	.register a{
		color: #514943;
	    font-weight: bold;
	    height: 30px;
	    text-decoration: none;
	}
	.welcome{
		float: right;
	    color: red;
	    font-weight: bold;
	    margin-right: 308px;
	    margin-top: 10px;
	}

</style>